apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wxrvg9m2k-nodejs 
  janus-idp.io/tekton: wxrvg9m2k-nodejs
  backstage.io/kubernetes-id: wxrvg9m2k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wxrvg9m2k-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml