apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wxrvg9m2k-nodejs
  janus-idp.io/tekton: wxrvg9m2k-nodejs
  backstage.io/kubernetes-id: wxrvg9m2k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wxrvg9m2k-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
